version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: apiretaurante
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: todo
    volumes:
      - todo-data:/data/db

volumes:
  todo-data:
